# Generated by Django 5.2.14 on 2026-05-14 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_jti', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.user')),
            ],
            options={
                'db_table': 'auth_sessions',
                'indexes': [models.Index(fields=['token_jti'], name='auth_sessio_token_j_3a5f3b_idx'), models.Index(fields=['user', 'revoked_at'], name='auth_sessio_user_id_f3b710_idx')],
            },
        ),
    ]
